In [1]:
import PIL
from PIL import Image
from numpy import asarray
import pandas as pd
import numpy as np

#https://www.geeksforgeeks.org/how-to-convert-images-to-numpy-array/
#converting pic to array

In [2]:
image = Image.open('testpic.jpg')

In [3]:
print(image.format)
print(image.size)
print(image.mode)

JPEG
(200, 200)
RGB


In [4]:
numpydata = asarray(image)
print(numpydata)

[[[239 244 247]
  [239 247 249]
  [241 250 249]
  ...
  [ 99 175 224]
  [138 205 250]
  [175 237 255]]

 [[239 244 247]
  [239 248 247]
  [240 249 248]
  ...
  [ 82 160 208]
  [111 184 229]
  [144 211 253]]

 [[239 244 247]
  [241 247 247]
  [240 249 248]
  ...
  [ 64 146 193]
  [ 84 163 206]
  [109 184 224]]

 ...

 [[238 207 186]
  [238 207 186]
  [237 206 185]
  ...
  [215 175 163]
  [215 175 163]
  [215 175 163]]

 [[238 207 186]
  [237 206 185]
  [237 206 185]
  ...
  [216 176 164]
  [216 176 164]
  [216 176 164]]

 [[237 206 185]
  [237 206 185]
  [236 205 184]
  ...
  [216 176 164]
  [216 176 164]
  [216 176 164]]]


In [5]:
print(numpydata[1][0][0])

239


In [25]:
print(numpydata[1][0][0])

239


In [26]:
filter11 = [-1,0,1],[-2,0,2],[-1,0,1]
filter12 = [1,2,1],[0,0,0],[-1,-2,-1]

In [27]:
print(filter12[0])

[1, 2, 1]


In [ ]:
convolution1 = []
convolution2 = []
count = 0
convocount = 0

#for q in range(0,66):
   # convolution1.append([])
    #for w in range(0,66):
     #   convolution1[q].append(0)

In [ ]:
print(convolution1[0][0])

In [43]:
x = 0
y = 1
z = 0

redNums = []
greenNums = []
blueNums = []
totalsum = 0

while(x <= 197):
    y = 1
    count = count + 1
    while(y <= 197):
        #count = count + 1
        #red
        redNums.append(filter11[0][0]*numpydata[x][y-1][z])
        redNums.append(filter11[0][1]*numpydata[x][y][z])
        redNums.append(filter11[0][2]*numpydata[x][y+1][z])
        
        redNums.append(filter11[1][0]*numpydata[x+1][y-1][z])
        redNums.append(filter11[1][1]*numpydata[x+1][y][z])
        redNums.append(filter11[1][2]*numpydata[x+1][y+1][z])
        
        redNums.append(filter11[2][0]*numpydata[x+2][y-1][z])
        redNums.append(filter11[2][1]*numpydata[x+2][y][z])
        redNums.append(filter11[2][2]*numpydata[x+2][y+1][z])
        
        Redsum = sum(redNums)
        
        
        ########green
        greenNums.append(filter11[0][0]*numpydata[x][y-1][z+1])
        greenNums.append(filter11[0][1]*numpydata[x][y][z+1])
        greenNums.append(filter11[0][2]*numpydata[x][y+1][z+1])
        
        greenNums.append(filter11[1][0]*numpydata[x+1][y-1][z+1])
        greenNums.append(filter11[1][1]*numpydata[x+1][y][z+1])
        greenNums.append(filter11[1][2]*numpydata[x+1][y+1][z+1])
        
        greenNums.append(filter11[2][0]*numpydata[x+2][y-1][z+1])
        greenNums.append(filter11[2][1]*numpydata[x+2][y][z+1])
        greenNums.append(filter11[2][2]*numpydata[x+2][y+1][z+1])
        
        Greensum = sum(greenNums)
        
        ##########blue
        blueNums.append(filter11[0][0]*numpydata[x][y-1][z+2])
        blueNums.append(filter11[0][1]*numpydata[x][y][z+2])
        blueNums.append(filter11[0][2]*numpydata[x][y+1][z+2])
        
        blueNums.append(filter11[1][0]*numpydata[x+1][y-1][z+2])
        blueNums.append(filter11[1][1]*numpydata[x+1][y][z+2])
        blueNums.append(filter11[1][2]*numpydata[x+1][y+1][z+2])
        
        blueNums.append(filter11[2][0]*numpydata[x+2][y-1][z+2])
        blueNums.append(filter11[2][1]*numpydata[x+2][y][z+2])
        blueNums.append(filter11[2][2]*numpydata[x+2][y+1][z+2])
        
        Bluesum = sum(blueNums)
        convocount = convocount + 1
        totalsum = Redsum + Greensum + Bluesum
        
        print(convolution1[x][y])
        convolution1[x][y]
        convolution1.append()
        #totalsum
        
        #print(count)
        #convolution1[x][y]
        #x = 3
        #y = 3
        #x = x + 1
        y = y + 1
    
    #print(count)
    #print("gello")
    x = x + 1
    

KeyboardInterrupt: 

In [33]:
print(redNums)
print(greenNums)
print(blueNums)

[-239, 0, 241, -478, 0, 480, -239, 0, 240, -239, 0, 241, -478, 0, 480, -241, 0, 239, -241, 0, 241, -480, 0, 480, -240, 0, 239, -241, 0, 243, -480, 0, 480, -239, 0, 239, -241, 0, 245, -480, 0, 488, -239, 0, 241, -243, 0, 249, -480, 0, 494, -239, 0, 243, -245, 0, 246, -488, 0, 494, -241, 0, 242, -249, 0, 239, -494, 0, 482, -243, 0, 239, -246, 0, 223, -494, 0, 452, -242, 0, 227, -239, 0, 209, -482, 0, 424, -239, 0, 214, -223, 0, 208, -452, 0, 414, -227, 0, 206, -209, 0, 206, -424, 0, 404, -214, 0, 195, -208, 0, 187, -414, 0, 360, -206, 0, 169, -206, 0, 164, -404, 0, 308, -195, 0, 144, -187, 0, 130, -360, 0, 216, -169, 0, 90, -164, 0, 106, -308, 0, 170, -144, 0, 74, -130, 0, 83, -216, 0, 138, -90, 0, 66, -106, 0, 77, -170, 0, 146, -74, 0, 80, -83, 0, 85, -138, 0, 182, -66, 0, 109, -77, 0, 103, -146, 0, 238, -80, 0, 143, -85, 0, 133, -182, 0, 312, -109, 0, 180, -103, 0, 166, -238, 0, 376, -143, 0, 210, -133, 0, 202, -312, 0, 428, -180, 0, 222, -166, 0, 217, -376, 0, 448, -210, 0, 231, -202,

In [18]:
redNums.clear()

In [31]:
Redsum = sum(redNums)
Greensum = sum(greenNums)
Bluesum = sum(blueNums)
print(Redsum)
print(Greensum)
print(Bluesum)

5
21
5


In [55]:
data = Image.fromarray(numpydata)

In [44]:
data.save('gfg_dummy_pic.png')